apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: dorinsdpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dorinsdpipelinesjavascriptdocker 
    spec:
      containers:
        - name: dorinsdpipelinesjavascriptdocker 
          image: dorinacr.azurecr.io/dorinsdpipelinesjavascriptdocker
          ports:
          - containerPort: 8080